server:
  port: 8080

spring:
  application:
    name: webrtc-signaling-server
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.study.webrtc: DEBUG
    org.springframework.web.socket: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"